# Generated by Django 2.1.7 on 2019-03-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOfficeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='title')),
            ],
            options={
                'verbose_name': 'open office group',
                'verbose_name_plural': 'open office groups',
            },
        ),
        migrations.CreateModel(
            name='OpenOfficeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='event start')),
                ('student', models.CharField(blank=True, max_length=250, null=True, verbose_name='student name')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sekretariat.OpenOfficeGroup')),
            ],
            options={
                'verbose_name': 'open office slot',
                'verbose_name_plural': 'open office slot',
                'ordering': ('start', 'group'),
                'default_related_name': 'slots',
            },
        ),
    ]
