# Generated by Django 2.1.7 on 2019-03-15 18:04

import django_powerbank.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sekretariat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openofficeslot',
            name='secret',
            field=django_powerbank.db.models.fields.SecretField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='openofficeslot',
            name='verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
