# Generated by Django 2.1.7 on 2019-03-15 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sekretariat', '0002_auto_20190315_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openofficeslot',
            old_name='secret',
            new_name='confirmation_secret',
        ),
        migrations.RenameField(
            model_name='openofficeslot',
            old_name='verified',
            new_name='confirmed',
        ),
    ]
