# Generated by Django 2.1.7 on 2019-03-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekretariat', '0003_auto_20190315_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openofficeslot',
            unique_together={('group', 'start')},
        ),
    ]
