# Generated by Django 2.1.7 on 2019-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekretariat', '0004_auto_20190316_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openofficeslot',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='email'),
        ),
    ]
