# Generated by Django 2.2.1 on 2019-05-10 14:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('group_no', models.PositiveSmallIntegerField(default=0, verbose_name='group')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='number')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ('group_no', 'number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('number', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='number')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'account group',
                'verbose_name_plural': 'account groups',
                'ordering': ('number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='amount')),
                ('spent', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='money spent')),
                ('available', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='money available')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(2019)], verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='month')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ('year', 'month'),
                'unique_together': {('year', 'month', 'account')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Approximate payment due date', verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=0, help_text='What is the total cost?', max_digits=6, verbose_name='amount')),
                ('title', models.CharField(default='Expenditure', help_text='Short distinguishing name for this expenditure', max_length=150, verbose_name='title')),
                ('description', models.TextField(help_text='Please describe and justify this expenditure.', verbose_name='description')),
                ('submitted', models.DateField(blank=True, null=True, verbose_name='submission date')),
                ('approval', models.NullBooleanField(verbose_name='approval')),
                ('account', models.ForeignKey(blank=True, help_text='Please select a budget that need to be decreased', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
                ('budget', models.ForeignKey(blank=True, help_text='Please select a budget that need to be decreased', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='Managers'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expenditure request',
                'verbose_name_plural': 'expenditure requests',
                'ordering': ('date', 'amount'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.AccountGroup'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=datetime.datetime.now, verbose_name='time stamp')),
                ('kind', models.PositiveSmallIntegerField(choices=[(100, 'Manager'), (200, 'Accountant'), (1000, 'Control')], verbose_name='approval step')),
                ('approval', models.NullBooleanField(verbose_name='approval')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='budget.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'decision',
                'verbose_name_plural': 'decisions',
                'default_related_name': 'decisions',
                'unique_together': {('request', 'kind')},
            },
        ),
    ]
