# Generated by Django 2.2.1 on 2019-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date', 'amount'), 'verbose_name': 'expenditure request', 'verbose_name_plural': 'expenditure requests'},
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(help_text='Short distinguishing name for this expenditure', max_length=150, verbose_name='title'),
        ),
    ]
