# Generated by Django 2.2.1 on 2019-06-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190513_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='request',
            new_name='application',
        ),
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together={('application', 'kind')},
        ),
    ]
