# Generated by Django 2.2.1 on 2019-06-02 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190602_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Please select a budget that need to be decreased', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='application',
            name='budget',
            field=models.ForeignKey(blank=True, help_text='Please select a budget that need to be decreased', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget', verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(help_text='Approximate payment due date that will determine the monthly budget.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='manager',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='Managers'), on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
    ]
