# Generated by Django 2.2.6 on 2019-10-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date', 'amount'), 'permissions': (('change_application_status', 'Can change the application status'),), 'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
    ]
