# Generated by Django 2.2.6 on 2019-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20191014_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Open'), (200, 'Placed'), (1000, 'Completed')], default=100, help_text='Processing status for procurement', verbose_name='application status'),
        ),
    ]
