# Generated by Django 2.2.6 on 2019-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20191015_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='awaiting',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(100, 'Manager'), (200, 'Accountant'), (1000, 'Control')], null=True, verbose_name='awaiting decision'),
        ),
    ]
