# Generated by Django 2.2.6 on 2019-12-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20191126_1914'),
        ('budget', '0014_auto_20191030_1929'),
    ]

    operations = [
    ]
